// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package wgctrl is a generated GoMock package.
package wg

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	wgtypes "golang.zx2c4.com/wireguard/wgctrl/wgtypes"
)

// MockWGClient is a mock of WGClient interface.
type MockWGClient struct {
	ctrl     *gomock.Controller
	recorder *MockWGClientMockRecorder
}

// MockWGClientMockRecorder is the mock recorder for MockWGClient.
type MockWGClientMockRecorder struct {
	mock *MockWGClient
}

// NewMockWGClient creates a new mock instance.
func NewMockWGClient(ctrl *gomock.Controller) *MockWGClient {
	mock := &MockWGClient{ctrl: ctrl}
	mock.recorder = &MockWGClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWGClient) EXPECT() *MockWGClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWGClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWGClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWGClient)(nil).Close))
}

// Devices mocks base method.
func (m *MockWGClient) Devices() ([]*wgtypes.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices")
	ret0, _ := ret[0].([]*wgtypes.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockWGClientMockRecorder) Devices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockWGClient)(nil).Devices))
}

// MockWGFactory is a mock of WGFactory interface.
type MockWGFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWGFactoryMockRecorder
}

// MockWGFactoryMockRecorder is the mock recorder for MockWGFactory.
type MockWGFactoryMockRecorder struct {
	mock *MockWGFactory
}

// NewMockWGFactory creates a new mock instance.
func NewMockWGFactory(ctrl *gomock.Controller) *MockWGFactory {
	mock := &MockWGFactory{ctrl: ctrl}
	mock.recorder = &MockWGFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWGFactory) EXPECT() *MockWGFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockWGFactory) New() (WGClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(WGClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockWGFactoryMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockWGFactory)(nil).New))
}
