// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/interface.go

// Package controllers is a generated GoMock package.
package controllers

import (
	reflect "reflect"
	sync "sync"
	time "time"
	db "wireguard_api/db"
	usecases "wireguard_api/usecases"

	gomock "github.com/golang/mock/gomock"
)

// MockServerRepo is a mock of ServerRepo interface.
type MockServerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockServerRepoMockRecorder
}

// MockServerRepoMockRecorder is the mock recorder for MockServerRepo.
type MockServerRepoMockRecorder struct {
	mock *MockServerRepo
}

// NewMockServerRepo creates a new mock instance.
func NewMockServerRepo(ctrl *gomock.Controller) *MockServerRepo {
	mock := &MockServerRepo{ctrl: ctrl}
	mock.recorder = &MockServerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerRepo) EXPECT() *MockServerRepoMockRecorder {
	return m.recorder
}

// CreateForward mocks base method.
func (m *MockServerRepo) CreateForward(position int, port, action, source, destination, protocol, comment string, isList, except bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForward", position, port, action, source, destination, protocol, comment, isList, except)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForward indicates an expected call of CreateForward.
func (mr *MockServerRepoMockRecorder) CreateForward(position, port, action, source, destination, protocol, comment, isList, except interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForward", reflect.TypeOf((*MockServerRepo)(nil).CreateForward), position, port, action, source, destination, protocol, comment, isList, except)
}

// CreateMasquerade mocks base method.
func (m *MockServerRepo) CreateMasquerade(source, ifname, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMasquerade", source, ifname, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMasquerade indicates an expected call of CreateMasquerade.
func (mr *MockServerRepoMockRecorder) CreateMasquerade(source, ifname, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMasquerade", reflect.TypeOf((*MockServerRepo)(nil).CreateMasquerade), source, ifname, comment)
}

// CreateServerCert mocks base method.
func (m *MockServerRepo) CreateServerCert(cert *db.ServerCert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServerCert", cert)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServerCert indicates an expected call of CreateServerCert.
func (mr *MockServerRepoMockRecorder) CreateServerCert(cert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerCert", reflect.TypeOf((*MockServerRepo)(nil).CreateServerCert), cert)
}

// DeleteForward mocks base method.
func (m *MockServerRepo) DeleteForward(comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForward", comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForward indicates an expected call of DeleteForward.
func (mr *MockServerRepoMockRecorder) DeleteForward(comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForward", reflect.TypeOf((*MockServerRepo)(nil).DeleteForward), comment)
}

// DeleteMasquerade mocks base method.
func (m *MockServerRepo) DeleteMasquerade(source, ifname, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMasquerade", source, ifname, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMasquerade indicates an expected call of DeleteMasquerade.
func (mr *MockServerRepoMockRecorder) DeleteMasquerade(source, ifname, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMasquerade", reflect.TypeOf((*MockServerRepo)(nil).DeleteMasquerade), source, ifname, comment)
}

// DeleteServer mocks base method.
func (m *MockServerRepo) DeleteServer(private, ifname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", private, ifname)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockServerRepoMockRecorder) DeleteServer(private, ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockServerRepo)(nil).DeleteServer), private, ifname)
}

// GetForward mocks base method.
func (m *MockServerRepo) GetForward() ([]db.Forward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForward")
	ret0, _ := ret[0].([]db.Forward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForward indicates an expected call of GetForward.
func (mr *MockServerRepoMockRecorder) GetForward() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForward", reflect.TypeOf((*MockServerRepo)(nil).GetForward))
}

// GetMasquerade mocks base method.
func (m *MockServerRepo) GetMasquerade() ([]db.Masquerade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasquerade")
	ret0, _ := ret[0].([]db.Masquerade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasquerade indicates an expected call of GetMasquerade.
func (mr *MockServerRepoMockRecorder) GetMasquerade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasquerade", reflect.TypeOf((*MockServerRepo)(nil).GetMasquerade))
}

// GetServerArchive mocks base method.
func (m *MockServerRepo) GetServerArchive() ([]db.ArchiveServerCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerArchive")
	ret0, _ := ret[0].([]db.ArchiveServerCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerArchive indicates an expected call of GetServerArchive.
func (mr *MockServerRepoMockRecorder) GetServerArchive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerArchive", reflect.TypeOf((*MockServerRepo)(nil).GetServerArchive))
}

// GetServerCertByIfname mocks base method.
func (m *MockServerRepo) GetServerCertByIfname(ifname string) (db.ServerCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerCertByIfname", ifname)
	ret0, _ := ret[0].(db.ServerCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerCertByIfname indicates an expected call of GetServerCertByIfname.
func (mr *MockServerRepoMockRecorder) GetServerCertByIfname(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerCertByIfname", reflect.TypeOf((*MockServerRepo)(nil).GetServerCertByIfname), ifname)
}

// GetServerCertificates mocks base method.
func (m *MockServerRepo) GetServerCertificates() ([]db.ServerCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerCertificates")
	ret0, _ := ret[0].([]db.ServerCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerCertificates indicates an expected call of GetServerCertificates.
func (mr *MockServerRepoMockRecorder) GetServerCertificates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerCertificates", reflect.TypeOf((*MockServerRepo)(nil).GetServerCertificates))
}

// GetServerInterfaces mocks base method.
func (m *MockServerRepo) GetServerInterfaces() ([]db.ServerCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerInterfaces")
	ret0, _ := ret[0].([]db.ServerCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerInterfaces indicates an expected call of GetServerInterfaces.
func (mr *MockServerRepoMockRecorder) GetServerInterfaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerInterfaces", reflect.TypeOf((*MockServerRepo)(nil).GetServerInterfaces))
}

// MockClientRepo is a mock of ClientRepo interface.
type MockClientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockClientRepoMockRecorder
}

// MockClientRepoMockRecorder is the mock recorder for MockClientRepo.
type MockClientRepoMockRecorder struct {
	mock *MockClientRepo
}

// NewMockClientRepo creates a new mock instance.
func NewMockClientRepo(ctrl *gomock.Controller) *MockClientRepo {
	mock := &MockClientRepo{ctrl: ctrl}
	mock.recorder = &MockClientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRepo) EXPECT() *MockClientRepoMockRecorder {
	return m.recorder
}

// CreateClientCert mocks base method.
func (m *MockClientRepo) CreateClientCert(cert *db.ClientCert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClientCert", cert)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClientCert indicates an expected call of CreateClientCert.
func (mr *MockClientRepoMockRecorder) CreateClientCert(cert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClientCert", reflect.TypeOf((*MockClientRepo)(nil).CreateClientCert), cert)
}

// DeleteClientCert mocks base method.
func (m *MockClientRepo) DeleteClientCert(public string) (db.ClientCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClientCert", public)
	ret0, _ := ret[0].(db.ClientCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClientCert indicates an expected call of DeleteClientCert.
func (mr *MockClientRepoMockRecorder) DeleteClientCert(public interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClientCert", reflect.TypeOf((*MockClientRepo)(nil).DeleteClientCert), public)
}

// GetAllClient mocks base method.
func (m *MockClientRepo) GetAllClient() ([]db.ClientCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllClient")
	ret0, _ := ret[0].([]db.ClientCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllClient indicates an expected call of GetAllClient.
func (mr *MockClientRepoMockRecorder) GetAllClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllClient", reflect.TypeOf((*MockClientRepo)(nil).GetAllClient))
}

// GetClientArchive mocks base method.
func (m *MockClientRepo) GetClientArchive() ([]db.ArchiveClientCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientArchive")
	ret0, _ := ret[0].([]db.ArchiveClientCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientArchive indicates an expected call of GetClientArchive.
func (mr *MockClientRepoMockRecorder) GetClientArchive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientArchive", reflect.TypeOf((*MockClientRepo)(nil).GetClientArchive))
}

// GetClientCertsByIfname mocks base method.
func (m *MockClientRepo) GetClientCertsByIfname(ifname string) ([]db.ClientCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientCertsByIfname", ifname)
	ret0, _ := ret[0].([]db.ClientCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientCertsByIfname indicates an expected call of GetClientCertsByIfname.
func (mr *MockClientRepoMockRecorder) GetClientCertsByIfname(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientCertsByIfname", reflect.TypeOf((*MockClientRepo)(nil).GetClientCertsByIfname), ifname)
}

// GetListIp mocks base method.
func (m *MockClientRepo) GetListIp(ifname string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListIp", ifname)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListIp indicates an expected call of GetListIp.
func (mr *MockClientRepoMockRecorder) GetListIp(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListIp", reflect.TypeOf((*MockClientRepo)(nil).GetListIp), ifname)
}

// GetPublicEnpointPort mocks base method.
func (m *MockClientRepo) GetPublicEnpointPort(ifname string) (db.ServerCert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicEnpointPort", ifname)
	ret0, _ := ret[0].(db.ServerCert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicEnpointPort indicates an expected call of GetPublicEnpointPort.
func (mr *MockClientRepoMockRecorder) GetPublicEnpointPort(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicEnpointPort", reflect.TypeOf((*MockClientRepo)(nil).GetPublicEnpointPort), ifname)
}

// MockIPTables is a mock of IPTables interface.
type MockIPTables struct {
	ctrl     *gomock.Controller
	recorder *MockIPTablesMockRecorder
}

// MockIPTablesMockRecorder is the mock recorder for MockIPTables.
type MockIPTablesMockRecorder struct {
	mock *MockIPTables
}

// NewMockIPTables creates a new mock instance.
func NewMockIPTables(ctrl *gomock.Controller) *MockIPTables {
	mock := &MockIPTables{ctrl: ctrl}
	mock.recorder = &MockIPTablesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPTables) EXPECT() *MockIPTablesMockRecorder {
	return m.recorder
}

// FlushForward mocks base method.
func (m *MockIPTables) FlushForward() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushForward")
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushForward indicates an expected call of FlushForward.
func (mr *MockIPTablesMockRecorder) FlushForward() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushForward", reflect.TypeOf((*MockIPTables)(nil).FlushForward))
}

// GetForwardList mocks base method.
func (m *MockIPTables) GetForwardList() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForwardList")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForwardList indicates an expected call of GetForwardList.
func (mr *MockIPTablesMockRecorder) GetForwardList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForwardList", reflect.TypeOf((*MockIPTables)(nil).GetForwardList))
}

// GetMasqueradeList mocks base method.
func (m *MockIPTables) GetMasqueradeList() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasqueradeList")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasqueradeList indicates an expected call of GetMasqueradeList.
func (mr *MockIPTablesMockRecorder) GetMasqueradeList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasqueradeList", reflect.TypeOf((*MockIPTables)(nil).GetMasqueradeList))
}

// SetForward mocks base method.
func (m *MockIPTables) SetForward(position int, port, action, command, source, destination, protocol, comment string, except bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForward", position, port, action, command, source, destination, protocol, comment, except)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForward indicates an expected call of SetForward.
func (mr *MockIPTablesMockRecorder) SetForward(position, port, action, command, source, destination, protocol, comment, except interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForward", reflect.TypeOf((*MockIPTables)(nil).SetForward), position, port, action, command, source, destination, protocol, comment, except)
}

// SetForwardList mocks base method.
func (m *MockIPTables) SetForwardList(position int, port, action, command, source, destination, protocol, comment string, except bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForwardList", position, port, action, command, source, destination, protocol, comment, except)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForwardList indicates an expected call of SetForwardList.
func (mr *MockIPTablesMockRecorder) SetForwardList(position, port, action, command, source, destination, protocol, comment, except interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForwardList", reflect.TypeOf((*MockIPTables)(nil).SetForwardList), position, port, action, command, source, destination, protocol, comment, except)
}

// SetMasquerade mocks base method.
func (m *MockIPTables) SetMasquerade(command, subnet, ifname, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasquerade", command, subnet, ifname, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasquerade indicates an expected call of SetMasquerade.
func (mr *MockIPTablesMockRecorder) SetMasquerade(command, subnet, ifname, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasquerade", reflect.TypeOf((*MockIPTables)(nil).SetMasquerade), command, subnet, ifname, comment)
}

// MockPingService is a mock of PingService interface.
type MockPingService struct {
	ctrl     *gomock.Controller
	recorder *MockPingServiceMockRecorder
}

// MockPingServiceMockRecorder is the mock recorder for MockPingService.
type MockPingServiceMockRecorder struct {
	mock *MockPingService
}

// NewMockPingService creates a new mock instance.
func NewMockPingService(ctrl *gomock.Controller) *MockPingService {
	mock := &MockPingService{ctrl: ctrl}
	mock.recorder = &MockPingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingService) EXPECT() *MockPingServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPingService) Delete(ip string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", ip)
}

// Delete indicates an expected call of Delete.
func (mr *MockPingServiceMockRecorder) Delete(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPingService)(nil).Delete), ip)
}

// Ping mocks base method.
func (m *MockPingService) Ping(target string, wg *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", target, wg)
}

// Ping indicates an expected call of Ping.
func (mr *MockPingServiceMockRecorder) Ping(target, wg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPingService)(nil).Ping), target, wg)
}

// Read mocks base method.
func (m *MockPingService) Read(ip string) (bool, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ip)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockPingServiceMockRecorder) Read(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockPingService)(nil).Read), ip)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteClient mocks base method.
func (m *MockService) DeleteClient(public string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", public)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockServiceMockRecorder) DeleteClient(public interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockService)(nil).DeleteClient), public)
}

// DeleteServer mocks base method.
func (m *MockService) DeleteServer(private, ifname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", private, ifname)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockServiceMockRecorder) DeleteServer(private, ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockService)(nil).DeleteServer), private, ifname)
}

// GetAllClients mocks base method.
func (m *MockService) GetAllClients() ([]usecases.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllClients")
	ret0, _ := ret[0].([]usecases.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllClients indicates an expected call of GetAllClients.
func (mr *MockServiceMockRecorder) GetAllClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllClients", reflect.TypeOf((*MockService)(nil).GetAllClients))
}

// GetClientArchive mocks base method.
func (m *MockService) GetClientArchive() ([]usecases.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientArchive")
	ret0, _ := ret[0].([]usecases.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientArchive indicates an expected call of GetClientArchive.
func (mr *MockServiceMockRecorder) GetClientArchive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientArchive", reflect.TypeOf((*MockService)(nil).GetClientArchive))
}

// GetIptablesRules mocks base method.
func (m *MockService) GetIptablesRules() (usecases.IptablesRulesData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIptablesRules")
	ret0, _ := ret[0].(usecases.IptablesRulesData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIptablesRules indicates an expected call of GetIptablesRules.
func (mr *MockServiceMockRecorder) GetIptablesRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIptablesRules", reflect.TypeOf((*MockService)(nil).GetIptablesRules))
}

// GetServerArchive mocks base method.
func (m *MockService) GetServerArchive() ([]usecases.ServerInterfaces, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerArchive")
	ret0, _ := ret[0].([]usecases.ServerInterfaces)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerArchive indicates an expected call of GetServerArchive.
func (mr *MockServiceMockRecorder) GetServerArchive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerArchive", reflect.TypeOf((*MockService)(nil).GetServerArchive))
}

// GetServerInterfaces mocks base method.
func (m *MockService) GetServerInterfaces() ([]usecases.ServerInterfaces, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerInterfaces")
	ret0, _ := ret[0].([]usecases.ServerInterfaces)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerInterfaces indicates an expected call of GetServerInterfaces.
func (mr *MockServiceMockRecorder) GetServerInterfaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerInterfaces", reflect.TypeOf((*MockService)(nil).GetServerInterfaces))
}

// GetStatus mocks base method.
func (m *MockService) GetStatus() ([]usecases.InterfaceListStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].([]usecases.InterfaceListStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockServiceMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockService)(nil).GetStatus))
}

// NewClient mocks base method.
func (m *MockService) NewClient(ifname, ip, allowed string) (usecases.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", ifname, ip, allowed)
	ret0, _ := ret[0].(usecases.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockServiceMockRecorder) NewClient(ifname, ip, allowed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockService)(nil).NewClient), ifname, ip, allowed)
}

// NewInterface mocks base method.
func (m *MockService) NewInterface(ifname, ip, endpoint string, port int) (usecases.ServerInterfaces, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewInterface", ifname, ip, endpoint, port)
	ret0, _ := ret[0].(usecases.ServerInterfaces)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewInterface indicates an expected call of NewInterface.
func (mr *MockServiceMockRecorder) NewInterface(ifname, ip, endpoint, port interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewInterface", reflect.TypeOf((*MockService)(nil).NewInterface), ifname, ip, endpoint, port)
}

// SetUsForward mocks base method.
func (m *MockService) SetUsForward(position int, action, command, source, destination, protocol, port, comment string, isList, except bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUsForward", position, action, command, source, destination, protocol, port, comment, isList, except)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUsForward indicates an expected call of SetUsForward.
func (mr *MockServiceMockRecorder) SetUsForward(position, action, command, source, destination, protocol, port, comment, isList, except interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUsForward", reflect.TypeOf((*MockService)(nil).SetUsForward), position, action, command, source, destination, protocol, port, comment, isList, except)
}

// SetUsMasquerade mocks base method.
func (m *MockService) SetUsMasquerade(command, source, ifname, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUsMasquerade", command, source, ifname, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUsMasquerade indicates an expected call of SetUsMasquerade.
func (mr *MockServiceMockRecorder) SetUsMasquerade(command, source, ifname, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUsMasquerade", reflect.TypeOf((*MockService)(nil).SetUsMasquerade), command, source, ifname, comment)
}

// StartInterface mocks base method.
func (m *MockService) StartInterface(ifname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartInterface", ifname)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartInterface indicates an expected call of StartInterface.
func (mr *MockServiceMockRecorder) StartInterface(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartInterface", reflect.TypeOf((*MockService)(nil).StartInterface), ifname)
}

// StopInterface mocks base method.
func (m *MockService) StopInterface(ifname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopInterface", ifname)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopInterface indicates an expected call of StopInterface.
func (mr *MockServiceMockRecorder) StopInterface(ifname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopInterface", reflect.TypeOf((*MockService)(nil).StopInterface), ifname)
}

// UpdateIpSetList mocks base method.
func (m *MockService) UpdateIpSetList(command, name string, ipList []string, single bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIpSetList", command, name, ipList, single)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIpSetList indicates an expected call of UpdateIpSetList.
func (mr *MockServiceMockRecorder) UpdateIpSetList(command, name, ipList, single interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIpSetList", reflect.TypeOf((*MockService)(nil).UpdateIpSetList), command, name, ipList, single)
}
