// Code generated by MockGen. DO NOT EDIT.
// Source: ping.go

// Package pingstatus is a generated GoMock package.
package pingstatus

import (
	net "net"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockICMPConn is a mock of ICMPConn interface.
type MockICMPConn struct {
	ctrl     *gomock.Controller
	recorder *MockICMPConnMockRecorder
}

// MockICMPConnMockRecorder is the mock recorder for MockICMPConn.
type MockICMPConnMockRecorder struct {
	mock *MockICMPConn
}

// NewMockICMPConn creates a new mock instance.
func NewMockICMPConn(ctrl *gomock.Controller) *MockICMPConn {
	mock := &MockICMPConn{ctrl: ctrl}
	mock.recorder = &MockICMPConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICMPConn) EXPECT() *MockICMPConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockICMPConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockICMPConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockICMPConn)(nil).Close))
}

// ReadFrom mocks base method.
func (m *MockICMPConn) ReadFrom(arg0 []byte) (int, net.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFrom", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(net.Addr)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadFrom indicates an expected call of ReadFrom.
func (mr *MockICMPConnMockRecorder) ReadFrom(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFrom", reflect.TypeOf((*MockICMPConn)(nil).ReadFrom), arg0)
}

// SetReadDeadline mocks base method.
func (m *MockICMPConn) SetReadDeadline(arg0 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReadDeadline", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReadDeadline indicates an expected call of SetReadDeadline.
func (mr *MockICMPConnMockRecorder) SetReadDeadline(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadDeadline", reflect.TypeOf((*MockICMPConn)(nil).SetReadDeadline), arg0)
}

// WriteTo mocks base method.
func (m *MockICMPConn) WriteTo(arg0 []byte, arg1 net.Addr) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTo", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteTo indicates an expected call of WriteTo.
func (mr *MockICMPConnMockRecorder) WriteTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTo", reflect.TypeOf((*MockICMPConn)(nil).WriteTo), arg0, arg1)
}

// MockICMPFactory is a mock of ICMPFactory interface.
type MockICMPFactory struct {
	ctrl     *gomock.Controller
	recorder *MockICMPFactoryMockRecorder
}

// MockICMPFactoryMockRecorder is the mock recorder for MockICMPFactory.
type MockICMPFactoryMockRecorder struct {
	mock *MockICMPFactory
}

// NewMockICMPFactory creates a new mock instance.
func NewMockICMPFactory(ctrl *gomock.Controller) *MockICMPFactory {
	mock := &MockICMPFactory{ctrl: ctrl}
	mock.recorder = &MockICMPFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICMPFactory) EXPECT() *MockICMPFactoryMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockICMPFactory) Listen() (ICMPConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen")
	ret0, _ := ret[0].(ICMPConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockICMPFactoryMockRecorder) Listen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockICMPFactory)(nil).Listen))
}
